### ISSUE TITLE
TensorFlow 2.0 wrapper should automatically profile tf.functions

### ISSUE THREAD

**Issue by parasj** [parasj/checkmate#118]
@aninrusimha 

We talked about integrating profiling into tf.function graph extraction. What is required to a) run a profiling iteration on the graph and b) correspond data from the TensorFlow profile with specific operations in the graph?

**Comment by aninrusimha** [comment]
The method I had used in the past relies on some holdover code from tensorflow 1.0, the in built profiler: 
https://www.tensorflow.org/api_docs/python/tf/compat/v1/profiler/profile
This method then matches the names of the ops to the timings for the ops for profiling.
