### ISSUE TITLE
Can I use it on a custom training loop?

### ISSUE THREAD

**Issue by left-brain** [parasj/checkmate#155]
I'm facing memory problems to train a GAN, and I would like to use checkmate to solve this, but in the tutorial it says to use “checkmate.tf.compile”, but I'm using the custom training loop, not model.fit nor model.compile, what to do in this situation?

**Comment by parasj** [comment]
Hi @left-brain 

Apologies for the delay! At the moment, the code on the `mlsys20_artifact` branch only supports Keras models. On master, there is partial support for more general TensorFlow graphs, but it may not work well with a custom training loop. I may try tracing your model's training iteration using `@tf.function` around the GradientTape context, but I am not sure how well this would work. We only tested the codebase with Keras models.

Thanks,
Paras
